# Site Settings
title: alina's resume
url: 'http://webjeda.com'
baseurl: '/asporea-cv' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6
style: styles-4
sass:
    sass_dir: assets/scss


#Profile information
name: Maria Alina Sporea
tagline: French/English sworn translator & interpreter
pic:
summary: 'Adaptive person, hardworker and very ambitious, excited to learn new things. Good points: quick learning, time management, responsibility, perfectionism.'

#sidebar links
#profile_picture_url:
email: alina.sporea@gmail.com
phone: 0745 045 059
#website: blog.webjeda.com #do not add http://
linkedin: alina-sporea
github: false
twitter: false
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
education_in_main: true
experience_in_main: true
projects_in_main: true
publications_in_main: false
footer_in_main: false

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development


gems:
  - jekyll-pdf
